os: linux

language: go

env: 
  - APP_DB_NAME=postgres
  - APP_DB_USERNAME=postgres
  - APP_DB_PASSWORD=''

go: 
  - 1.14.x

services: 
  - postgresql
  - docker

script: 
  - sem-service start postgres
  - go test -v

